name: build site-main

on:
  workflow_dispatch:
  
env:
  REGISTRY: ghcr.io/srd424
#  IMAGE_NAME: ${{ github.repository }}
  IMAGE_NAME: srd424/bnpi-site-main
  
jobs:
  build-all:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: cache build cache
      uses: actions/cache@v3
      with:
        path: cache
        key: bnpi0-modules
        restore-keys: |
          bnpi0-modules
          bnpi0-
          bnpi
    - name: Build all with buildah
      run: |
        mkdir -p cache/pip cache/apt cache/git \
          cache/apt-lists cache/caddy logs && \
        make OPTSFILE=gha
    - name: fix cache ownership
      run: sudo bash -c "chown -v -R \$SUDO_USER cache"
    - name: Log in to the Container registry
      uses: redhat-actions/podman-login@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish site-main
      run: podman push bnpi-site-main:latest ${{ env.REGISTRY }}/bnpi-site-main:amd64
    - name: Publish server
      run: podman push bnpi-server:latest ${{ env.REGISTRY }}/bnpi-server:amd64
# vim: set ts=2 et sw=2: ai 
