name: build all

on:
  workflow_dispatch:
  
env:
  REGISTRY: ghcr.io/srd424
  IMAGE_TAG: amd64
  
jobs:
  build-all:
    runs-on: ubuntu-22.04
    steps:
    - name: install new fuse-overlayfs
      run: |
        sudo dpkg-divert --local --rename /usr/bin/fuse-overlayfs && \
          curl -L https://github.com/containers/fuse-overlayfs/releases/download/v1.12/fuse-overlayfs-x86_64 -o /tmp/fuse-overlayfs && \
          sudo mv /tmp/fuse-overlayfs /usr/local/bin && \
          sudo chmod a+x /usr/local/bin/fuse-overlayfs
    - name: Checkout source
      uses: actions/checkout@v2
    - name: cache build cache
      uses: actions/cache@v3
      with:
        path: cache
        key: bnpi0-modules
        restore-keys: |
          bnpi0-modules
          bnpi0-
          bnpi
    - name: Build all with buildah
      run: |
        mkdir -p cache/pip cache/apt cache/git \
          cache/apt-lists cache/caddy logs && \
          buildah --version && \
        make OPTSFILE=gha
    - name: fix cache ownership
      run: sudo bash -c "chown -v -R \$SUDO_USER cache"
    - name: Log in to the Container registry
      uses: redhat-actions/podman-login@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish site-main
      run: podman push bnpi-site-main:latest ${{ env.REGISTRY }}/bnpi-site-main:${{ env.IMAGE_TAG }}
    - name: Publish server
      run: podman push bnpi-server:latest ${{ env.REGISTRY }}/bnpi-server:${{ env.IMAGE_TAG }}
# vim: set ts=2 et sw=2: ai 
