name: build birdnetpi docker

on:
  workflow_dispatch:
  
env:
  REGISTRY: ghcr.io
#  IMAGE_NAME: ${{ github.repository }}
  IMAGE_NAME: srd424/bnpi-server
  
jobs:
  builder-build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: cache build cache
      uses: actions/cache@v3
      with:
        path: cache
        key: bnpi0-modules
        restore-keys: |
          bnpi0-modules
          bnpi0-
          bnpi
    - name: Build with buildah
      run: |
        mkdir -p cache/pip cache/apt cache/git \
          cache/apt-lists && \
        buildah bud \
          -v $PWD/cache/apt:/var/cache/apt/archives \
          -v $PWD/cache/pip:/home/pi/.cache/pip \
          -v $PWD/cache/apt-lists:/var/lib/apt/lists \
          -v $PWD/cache/git:/home/pi/gitcache \
          --build-arg MODULES="server" \
          --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:amd64 .
    - name: fix cache ownership
      run: sudo bash -c "chown -v -R \$SUDO_USER cache"
    - name: Log in to the Container registry
      uses: redhat-actions/podman-login@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish image
      run: podman push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:amd64
